all: dodawanie odejmowanie

dodawanie: dodawanie.s
	as dodawanie.s --gstabs -o dodawanie.o	
	ld dodawanie.o -o dodawanie

odejmowanie: odejmowanie.s
	as odejmowanie.s --gstabs -o odejmowanie.o	
	ld odejmowanie.o -o odejmowanie


